labels:
  - name: "type:idea"
    color: "5319e7"
    description: "创意征集 / Idea intake"
  - name: "type:feature"
    color: "1d76db"
    description: "功能请求或增强 / Feature request"
  - name: "type:bug"
    color: "d73a4a"
    description: "缺陷或异常 / Bug report"
  - name: "status:triage"
    color: "cfd3d7"
    description: "等待分诊 / Awaiting triage"
  - name: "status:in-review"
    color: "fbca04"
    description: "评审中 / In review"
  - name: "status:stale"
    color: "d4c5f9"
    description: "久未更新 / Stale item"
  - name: "good-first-issue"
    color: "7057ff"
    description: "适合首次贡献者 / Good first issue"
  - name: "help-wanted"
    color: "008672"
    description: "需要协作者 / Help wanted"
  - name: "area:frontend"
    color: "c5def5"
    description: "前端相关 / Frontend scope"
  - name: "area:backend"
    color: "f9d0c4"
    description: "后端或服务 / Backend scope"
  - name: "area:infra"
    color: "fef2c0"
    description: "基础设施 / Infrastructure"
  - name: "area:docs"
    color: "bfdadc"
    description: "文档与写作 / Documentation"
  - name: "priority:p1"
    color: "b60205"
    description: "高优先级 / High priority"
  - name: "priority:p2"
    color: "d93f0b"
    description: "中优先级 / Medium priority"
  - name: "priority:p3"
    color: "f9c513"
    description: "低优先级 / Low priority"
  - name: "status:done"
    color: "0e8a16"
    description: "已完成 / Done"
