services:
  postgres:
    image: postgres:16-alpine
    container_name: magic_conch_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-graveyard}
      POSTGRES_USER: ${POSTGRES_USER:-graveyard_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-graveyard_pass}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-graveyard_user} -d ${POSTGRES_DB:-graveyard}"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: magic_conch_graveyard
    ports:
      - "8000:8000"
    volumes:
      - ./storage:/app/storage
      - ./data:/app/data
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    command: >
      sh -c "python scripts/init_db.py &&
             python scripts/import_entries.py &&
             uvicorn server.app:app --host 0.0.0.0 --port 8000"

volumes:
  postgres_data:
