name: "✨ Feature Request | 功能请求"
description: "提议新的功能或改进。Suggest a new feature or enhancement."
title: "Feature: "
labels:
  - "type:feature"
  - "status:triage"
body:
  - type: textarea
    id: context
    attributes:
      label: "背景与问题 | Context"
      description: "描述当前体验与痛点。Describe the current experience and pain."
      placeholder: "当我尝试...\nWhen I try..."
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: "期望的解决方案 | Desired Solution"
      description: "写下你心中的理想功能。Describe your ideal solution."
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: "考虑过的替代方案 | Alternatives"
      description: "列出其他尝试或放弃理由。List alternatives you've considered."
  - type: textarea
    id: scope
    attributes:
      label: "影响范围 | Impact"
      description: "谁会受益？是否影响现有流程？Who benefits? Any process impact?"
  - type: checkboxes
    id: checklist
    attributes:
      label: "确认 Checklist"
      options:
        - label: "我已搜索过相关 Issue / I have searched for related issues."
          required: true
        - label: "此请求与神奇海螺的愿景一致 / Aligns with Magic Conch vision."
        - label: "我愿意协助设计或实现 / I can help design/implement."
