name: Refresh Leaderboard

on:
  push:
    branches: [main]
    paths:
      - 'graveyard/entries/**'
      - 'scripts/generate_leaderboard.py'
      - 'README.md'
      - 'badges/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-leaderboard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Generate leaderboard
        run: python scripts/generate_leaderboard.py
      - name: Commit leaderboard updates
        run: |
          if git diff --quiet README.md badges/README-badges.md; then
            echo "No leaderboard changes detected."
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md badges/README-badges.md
          git commit -m "chore: refresh graveyard leaderboard"
      - name: Push changes
        run: git push
