name: Validate Graveyard Entry

on:
  pull_request:
    paths:
      - 'graveyard/entries/**'
      - 'graveyard/schema.md'
      - 'scripts/validate_entries.py'
      - 'requirements.txt'
  workflow_dispatch:

jobs:
  schema-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Validate graveyard entries
        run: python scripts/validate_entries.py
